### ISSUE TITLE
har-validator not found

### ISSUE THREAD

**Issue by chrisabrams** [0xProject/0x-launch-kit-backend#11]
When running `yarn` or `yarn install`:

    error An unexpected error occurred: "https://registry.yarnpkg.com/har-validator/-/har-validator-5.1.2.tgz: Request failed \"404 Not Found\"".

**Comment by robinsingh1** [comment]
https://github.com/ahmadnassri/node-har-validator/issues/112#issuecomment-437378269

Ran into this as well - comment above helped resolve the issue, some packages in the yarn.lockfile have been unpublished from npm

**Comment by fabioberger** [comment]
Thanks for the heads up. Will try and address this ASAP.

**Comment by juliusbuckley** [comment]
`rm yarn.lock` and then run `yarn`. the yarn.lock will be generated again and work properly for a temp fix.

**Comment by LogvinovLeon** [comment]
Should be fixed now.
