### ISSUE TITLE
typeorm error on curl http://localhost:3000/v2/orders (js codebase)

### ISSUE THREAD

**Issue by juliusbuckley** [0xProject/0x-launch-kit-backend#15]
After running `yarn start:js` and `curl http://localhost:3000/v2/orders`, the following error is displayed.

`EntityMetadataNotFound: No metadata for "SignedOrderModel" was found.`

This error is only an issue when using the js codebase. When using the ts codebase there are no typeorm errors.

**Comment by fabioberger** [comment]
Thanks for the bug report @juliusbuckley, we will look into this first thing Monday.

**Comment by jkanche** [comment]
In addition to the error from the original post, I also see the following messages in the console 

> { code: -32602,
>   message: 'Invalid params: unknown field `blockHash`, expected one of `fromBlock`, `toBlock`, `address`, `topics`, `limit`.' }

**Comment by LogvinovLeon** [comment]
@jkanche Which node are you using? `blockHash` is supported in Geth > v1.8.13 and Parity > v2.1.0. Infura works too.

**Comment by fabioberger** [comment]
@LogvinovLeon let's add the backing node requirements to the README.
