### ISSUE TITLE
OrderWatcher issue 

### ISSUE THREAD

**Issue by amyrprv** [0xProject/0x-launch-kit-backend#26]
Hello,
I add order using `/v2/order` api and i fill the order from my application but the order is still returned from `/v2/orderbook` API

**Comment by fabioberger** [comment]
@amirh3n thanks for opening an issue. Did you fill the order in it's entirety?

**Comment by amyrprv** [comment]
@fabioberger Yes, and another thing which i forgot to mention was I'm getting also expired orders from API

**Comment by fabioberger** [comment]
What API? Radar? If so, that is a known issue with their SRA implementation.

**Comment by amyrprv** [comment]
@fabioberger No, I use `/v2/order` in 0x-launch-kit to post an order, When the order is expired I still receive it from `/v2/orderbook` API in 0x-launch-kit

**Comment by fabioberger** [comment]
I see, that is definitively a bug. We will try and get a fix out soon. If you want to attempt to fix it, we'd be happy to accept a pull request.

**Comment by pelsasser** [comment]
@fabioberger I am attempting to follow the code base, and from my very basic understanding of how this is working it looks like the orders do not get added to the map to be "shadowed"

https://github.com/0xProject/0x-launch-kit/blob/1e9fb170513eac6c9a8e2a7cb7e4052853707330/ts/src/orderbook.ts#L24

I am gonna keep looking at it for a bit to make sure I understand the purpose of that map.

**Comment by pelsasser** [comment]
perhaps "shadowed" means orders that are no longer valid looking at this again.

**Comment by dekz** [comment]
This is likely a result of the issue described in #28.

**Comment by 0xean** [comment]
There are several other issues going on in the orderwatcher and the pruning functionality as well.

A few of the issues
- once an order is added to the shadowedOrders map, it is never removed, even after pruning
- orders never get removed from the orderWatcher even after deleted from the dB
- The docs don't make it clear, but you need to update the the RPC_URL in the config, otherwise the whole thing just fails silently and never connects to the provider.

**Comment by michaelhly** [comment]
I still have pruning issues...

FULLY_FILLED orders such as this one: 
`
{"signature":"0x1b4e68109968df179fa10ad337109996a576a6bf6bb167b27576588583a33109581e27ede5683eb8b0a9c2ff5518b0174f0f7efaa09f48a9faf327f8d5f712a99803","senderAddress":"0x0000000000000000000000000000000000000000","makerAddress":"0xc4d7598b59b400c3245693003c5d047f1ac430dc","takerAddress":"0x0000000000000000000000000000000000000000","makerFee":"0","takerFee":"0","makerAssetAmount":"1000000000000000","takerAssetAmount":"1000000000000000","makerAssetData":"0xf47261b00000000000000000000000004a1f5f67c1cf90f176496aa548382c78921ae9f1","takerAssetData":"0xf47261b0000000000000000000000000c4abc01578139e2105d9c9eba0b0aa6f6a60d082","salt":"36842753527106273017921939367969941505762495036753407130125656162133848680214","exchangeAddress":"0xbce0b5f6eb618c565c3e5f5cd69652bbc279f44e","feeRecipientAddress":"0x0000000000000000000000000000000000000000","expirationTimeSeconds":"1548930090088"}
`
 are still returned from /v2/orderbook/.... as shown [here](https://imgur.com/a/96vnm7H). 


Status from codesandbox: https://imgur.com/a/s6x9MvM
Etherscan: https://rinkeby.etherscan.io/tx/0x0549617863ec9301d9f540513f81f246ccd553e427239d79dd9138e598b03b2e

**Comment by fabioberger** [comment]
Thanks for letting us know about these issues @pelsasser, @amirh3n and @michaelhly. Working on a PR to address all of them.

**Comment by fabioberger** [comment]
Issues have been fixed in #44
