### ISSUE TITLE
ERC721 asset pairs

### ISSUE THREAD

**Issue by dekz** [0xProject/0x-launch-kit-backend#27]
The token id should be stripped out of the asset pairs endpoint so that only a single asset pair per contract is returned. 

## Current Behaviour
Adding 10 ERC721 Axie orders would result in 10 different asset pairs.

## Expected Behaviour
1 Asset pair per ERC721 contract

**Comment by fabioberger** [comment]
This is actually the expected behavior as stated in the SRA spec. How is this causing you grief?
