### ISSUE TITLE
/v2/fee_recipients: validation error on feeRecipients

### ISSUE THREAD

**Issue by laurengarcia** [0xProject/0x-launch-kit-backend#33]
Querying this endpoint via curl is fine but returns a schema error when queried via 0x Connect:
`client.getFeeRecipientsAsync()`
```
Error: Expected feeRecipients to conform to schema /relayerApiFeeRecipientsResponseSchema
Encountered: {
	"total": 1,
	"page": 0,
	"perPage": 20,
	"records": [
		"0x4448FC893284740551a5F776b4EC42cA0B010a1B"
	]
}
Validation errors: instance does not match allOf schema [subschema 1] with 1 error[s]:, instance.records[0] does not match pattern "^0x[0-9a-f]{40}$"
    at Object.assert (/Users/lauren/github/0x-hackathon/node_modules/@0x/assert/lib/src/index.js:76:19)
    at Object.doesConformToSchema (/Users/lauren/github/0x-hackathon/node_modules/@0x/assert/lib/src/index.js:64:24)
```

curl queries are fine:
`curl 'http://localhost:3000/v2/fee_recipients'
{"total":1,"page":0,"perPage":20,"records":["0x4448FC893284740551a5F776b4EC42cA0B010a1B"]}`

**Comment by dekz** [comment]
@laurengarcia thanks again. We usually lower case addresses as it can influence the order hash and is best to stick to one (either lower cased or checksummed). 

Can you confirm if the order that was published used this checksummed address and not the lower case address, that is the order has `0x4448FC893284740551a5F776b4EC42cA0B010a1B` not `0x4448fc893284740551a5f776b4ec42ca0b010a1b` (lower case).

**Comment by laurengarcia** [comment]
Gotcha, I see what happened. The validation error was throwing from 0x Connect's `.getFeeRecipientsAsync` which checks the config.ts file `FEE_RECIPIENT`, where I had probably copy/pasted the non-lowercased version from either Metamask or Etherscan. Was not aware of the lowercase convention, but I can see it now because all of the bid/ask records in my Launch Kit instance appear to be lowercased as well.

When I .toLowerCase() the `FEE_RECIPIENT` address in config.ts and then query via 0x Connect's `.getFeeRecipientsAsync()` now there is no error.

Am going to add a comment to my local config file about lowercasing it, might want to consider doing that for 0x noobs :)

Thanks again!

**Comment by dekz** [comment]
Yep I think we can lowercase it in launch kit safely.
