### ISSUE TITLE
Sort orderbook by price

### ISSUE THREAD

**Issue by dekz** [0xProject/0x-launch-kit-backend#41]
SRA Docs:

> Bids will be sorted in descending order by price, and asks will be sorted in ascending order by price. Within the price sorted orders, the orders are further sorted by taker fee price which is defined as the takerFee divided by takerTokenAmount. After taker fee price, orders are to be sorted by expiration in ascending order.

**Comment by BlinkyStitt** [comment]
How are they currently sorted?
