### ISSUE TITLE
asset_pairs question

### ISSUE THREAD

**Issue by aakilfernandes** [0xProject/0x-launch-kit-backend#51]
Hey, is asset_pairs supposed to give a list of supported asset pairs, or a list of asset_pairs which currently have maker orders

**Comment by dekz** [comment]
It's fairly ambiguous reading the SRA specification. Internally we have decided that `asset_pairs` returns what is available. 

If you think this is confusing or incorrect I'd like to get your feed back at the [SRA repository](https://github.com/0xProject/standard-relayer-api/issues),

**Comment by aakilfernandes** [comment]
Closed in favor of https://github.com/0xProject/standard-relayer-api/issues/48
