### ISSUE TITLE
Fee clarification

### ISSUE THREAD

**Issue by aakilfernandes** [0xProject/0x-launch-kit-backend#53]
Hey, in the fee config, does `1` refer to 1 ZRX or 10^-18 ZRX

https://github.com/0xProject/0x-launch-kit/blob/master/ts/src/config.ts#L37
https://github.com/0xProject/0x-launch-kit/blob/master/ts/src/config.ts#L41

**Comment by dekz** [comment]
`1` unit refers to `1 ZRX`. `1` Base unit is 10^-18 ZRX. `0.01` is valid for this parameter.

**Comment by aakilfernandes** [comment]
Got it. Thanks!
