### ISSUE TITLE
Lost order in db when restart container

### ISSUE THREAD

**Issue by alessiofx** [0xProject/0x-launch-kit-backend#64]
When you restart the container all the orders on the database are lost.
You can fix this problem.

**Comment by fabioberger** [comment]
You can do this by mounting a volume to the Docker container where the `database.sql` file is stored so that it persists across container re-starts. We can add instructions to the README on how to do this. Thanks for the suggestion.

**Comment by dekz** [comment]
This will be possible once 0xProject/0x-launch-kit-backend#65 is merged. Currently you can mount from local but not allocate a persistent volume.

**Comment by dekz** [comment]
A Docker volume can now be attached to the backend to allow for persistent orders through restarts
```yaml
backend:
    ...
    volumes:
      - backend-database:/usr/app/src/db
```
